const data = {
    name: [
        'breakfast',
        'saladsAndSnacks',
        'soups',
        'burgers',
        'maindishes',
        'desserts',
        'drinks',
        'drinks',
    ],
    id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    ru: {
        Завтраки: [
            {
                id: 28,
                name: 'Яичница – глазунья с добавками на выбор',
                price: 320,
                description: 'лук, бекон, грибы, сыр, томаты, зелень',
            },
            {
                id: 29,
                name: 'Омлет с добавками на выбор',
                price: 350,
                description: 'лук, бекон, грибы, сыр, томаты, зелень',
            },
            {
                id: 30,
                name: 'Яйца бенедикт с беконом и голландским соусом',
                price: 390,
                description: '',
            },
            {
                id: 31,
                name: 'Яйца роял с лососем, шпинатом и голландским соусом',
                price: 490,
                description: '',
            },
            {
                id: 32,
                name: 'Оладьи из цуккини с лососем и рикоттой',
                price: 490,
                description: '',
            },
            {
                id: 33,
                name: 'Каша овсяная',
                price: 300,
                description: '',
            },
            {
                id: 34,
                name: 'Асаи боул',
                price: 350,
                description: '',
            },
            {
                id: 35,
                name: 'Блинчики по-русски',
                price: 300,
                description:
                    'подаются со сметаной и домашним вареньем',
            },
            {
                id: 36,
                name: 'Хрустящие бельгийские вафли',
                price: 330,
                description: '',
            },
            {
                id: 37,
                name: 'Сырники с сезонными ягодами и сметаной',
                price: 350,
                description: '',
            },
            {
                id: 38,
                name: 'Красная икра с блинами',
                price: 840,
                description: '',
            },
            {
                id: 8,
                name: 'Икра осетровая с блинами',
                price: 7200,
                description: '50 гр',
            },
        ],
        'Салаты и закуски': [
            {
                id: 1,
                name: 'Тост с лососем и цуккини',
                price: 760,
                description: '',
            },
            {
                id: 2,
                name: 'Тост с авокадо и яйцом пашот',
                price: 690,
                description: '',
            },
            {
                id: 3,
                name: 'Итальянский сет к вину',
                price: 1200,
                description:
                    'Итальянские колбасы и сыры, артишоки гриль, оливки, кростини',
            },
            {
                id: 4,
                name: 'Цезарь с цыпленком',
                price: 750,
                description: '',
            },
            {
                id: 5,
                name: 'Цезарь с креветками',
                price: 880,
                description: '',
            },
            {
                id: 6,
                name: 'Теплый салат с говядиной',
                price: 710,
                description: '',
            },
            {
                id: 7,
                name: 'Салат из сезонных овощей с халуми',
                price: 740,
                description: '',
            },
        ],
        Супы: [
            {
                id: 9,
                name: ' Борщ с пампушками и сметаной',
                price: 640,
                description: '',
            },
            {
                id: 10,
                name: 'Куриный суп с домашней лапшой',
                price: 520,
                description: '',
            },
        ],
        'Бургеры и сендвичи': [
            {
                id: 11,
                name: 'Кайенский бургер',
                price: 1200,
                description:
                    'Котлета из мраморной говядины, овощи гриль, соус с кайенским перцем. Подается с картофелем фри и домашними соусами',
            },
            {
                id: 12,
                name: 'Domina чизбургер',
                price: 1200,
                description:
                    'Котлета из мраморной говядины, Чеддер, огуречный релиш. Подается с картофелем фри и домашними соусами',
            },
            {
                id: 13,
                name: 'Врап с цыпленком',
                price: 750,
                description: '',
            },
            {
                id: 14,
                name: 'Клубный сэндвич',
                price: 980,
                description:
                    'Подается с картофелем фри и домашними соусами',
            },
        ],
        'Горячие блюда': [
            {
                id: 15,
                name: 'Палтус с кремом из баклажана',
                price: 1350,
                description: '',
            },
            {
                id: 16,
                name: 'Фланк стейк с битым картофелем',
                price: 1100,
                description: '',
            },
            {
                id: 17,
                name: 'Соте из креветок и кальмара',
                price: 1300,
                description: '',
            },
            {
                id: 18,
                name: 'Спагетти карбонара',
                price: 720,
                description: '',
            },
            {
                id: 19,
                name: 'Ригатони качо э пепе',
                price: 650,
                description: '',
            },
            {
                id: 20,
                name: 'Хрустящий баклажан',
                price: 640,
                description: '',
            },
        ],
        Десерты: [
            {
                id: 21,
                name: 'Шоколадный брауни с мороженым',
                price: 550,
                description: '',
            },
            {
                id: 22,
                name: 'Наполеон',
                price: 510,
                description: '',
            },
            {
                id: 23,
                name: 'Фруктовая тарелка',
                price: 900,
                description: '',
            },
            {
                id: 24,
                name: 'Ассорти итальянских сыров',
                price: 950,
                description: '',
            },
            {
                id: 25,
                name: 'Домашнее мороженое и сорбеты',
                price: 650,
                description: '',
            },
        ],
        'Безалкогольные напитки': [
            {
                id: 26,
                name: 'Свежевыжатый апельсиновый сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 27,
                name: 'Свежевыжатый грейпфрутовый сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 39,
                name: 'Свежевыжатый яблочный сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 40,
                name: 'Свежевыжатый морковный сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 41,
                name: 'Свежевыжатый ананасовый сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 42,
                name: 'Свежевыжатый сельдереевый сок',
                price: 350,
                description: '250 мл',
            },
            {
                id: 43,
                name: 'Минеральная вода San Benedetto',
                price: 390,
                description: '250 мл',
            },
            {
                id: 44,
                name: 'Минеральная вода San Benedetto',
                price: 750,
                description: '750 мл',
            },
            {
                id: 45,
                name: 'Эспрессо',
                price: 250,
                description: '',
            },
            {
                id: 46,
                name: 'Американо',
                price: 250,
                description: '',
            },
            {
                id: 47,
                name: 'Капучино',
                price: 300,
                description: '',
            },
            {
                id: 48,
                name: 'Латте',
                price: 300,
                description: '',
            },
            {
                id: 49,
                name: 'Чёрный чай',
                price: 400,
                description: '400 мл',
            },
            {
                id: 50,
                name: 'Зелёный чай',
                price: 350,
                description: '400 мл',
            },
            {
                id: 51,
                name: 'Чай фруктовый и травяной',
                price: 350,
                description: '400 мл',
            },
        ],
        'Алкогольные напитки': [
            {
                id: 52,
                name: 'Бутылочное пиво Budels Capucijn',
                price: 580,
                description: '330 мл',
            },
            {
                id: 53,
                name: 'Бутылочное пиво Budels Witte Parel',
                price: 580,
                description: '330 мл',
            },
            {
                id: 54,
                name: 'Яблочный сидр Royal Demi-Sec Cider',
                price: 420,
                description: '330 мл',
            },
            {
                id: 82,
                name: 'Безалкогольное пиво Budels Malt',
                price: 420,
                description: '330 мл',
            },
            {
                id: 55,
                name: 'Вермут Martini Bianco',
                price: 350,
                description: '50 мл',
            },
            {
                id: 56,
                name: 'Биттер Jagermeister',
                price: 560,
                description: '50 мл',
            },
            {
                id: 57,
                name: 'Водка Абсолют',
                price: 350,
                description: '50 мл',
            },
            {
                id: 58,
                name: 'Водка Beluga',
                price: 490,
                description: '50 мл',
            },
            {
                id: 59,
                name: 'Джин Beefeater',
                price: 650,
                description: '50 мл',
            },
            {
                id: 60,
                name: 'Ром Angostura 5 y.o.',
                price: 500,
                description: '50 мл',
            },
            {
                id: 61,
                name: 'Виски The Macallan 12 y.o.',
                price: 1600,
                description: '50 мл',
            },
            {
                id: 62,
                name: 'Виски Chivas Regal 12 y.o.',
                price: 990,
                description: '50 мл',
            },
            {
                id: 63,
                name: 'Виски Jameson',
                price: 690,
                description: '50 мл',
            },
            {
                id: 64,
                name: 'Виски Jack Daniel’s',
                price: 750,
                description: '50 мл',
            },
            {
                id: 65,
                name: 'Коньяк Hennessy Very Special',
                price: 1050,
                description: '50 мл',
            },
            {
                id: 66,
                name: 'Вино игристое PROSECCO Cielo Brut, Veneto, Italy',
                price: 3900,
                description: '750 мл',
            },
            {
                id: 67,
                name: 'Вино игристое CRÉMANT D’ALSACE Wolfberger Brut Rosé, Alsace, France',
                price: 7900,
                description: '750 мл',
            },
            {
                id: 68,
                name: 'Шампанское Moët & Chandon Brut Imperial, France',
                price: 16500,
                description: '750 мл',
            },
            {
                id: 69,
                name: 'Шампанское Moët & Chandon Rosé Brut Imperial, France',
                price: 19500,
                description: '750 мл',
            },
            {
                id: 70,
                name: 'Шампанское Veuve Cliquot Brut St.Petersburg, France',
                price: 17500,
                description: '750 мл',
            },
            {
                id: 71,
                name: 'Белое вино GRUNER VELTLINER Nastl Kittmannsberg, Austria',
                price: 5400,
                description: '750 мл',
            },
            {
                id: 72,
                name: 'Белое вино SAUVIGNON BLANC Spencer Hill ‘Latitude 41’, New Zealand',
                price: 5900,
                description: '750 мл',
            },
            {
                id: 73,
                name: 'Белое вино PINOT GRIGIO Elena Walch, Italy',
                price: 6700,
                description: '750 мл',
            },
            {
                id: 74,
                name: 'Белое вино CHABLIS Jean-Marc Brocard Sainte-Claire, Burgundy, France',
                price: 8200,
                description: '750 мл',
            },
            {
                id: 75,
                name: 'Белое вино PINOT GRIS Moenchberg Grand Cru ‘Le Moine’, Alsace, France',
                price: 12500,
                description: '750 мл',
            },
            {
                id: 76,
                name: 'Вино красное ZWEIGELT Blauer Nittnaus, Austria',
                price: 5400,
                description: '750 мл',
            },
            {
                id: 77,
                name: 'Вино красное ZINFANDEL ‘Old Vine Zin’ Gnarly Head, California',
                price: 6400,
                description: '750 мл',
            },
            {
                id: 78,
                name: 'Вино красное CHIANTI Classico ReservaSan Felice il Grigio, Toscana',
                price: 81000,
                description: '750 мл',
            },
            {
                id: 79,
                name: 'Вино красное SEXY BEAST Two Hands, McLaren Vale, Australia',
                price: 9300,
                description: '750 мл',
            },
            {
                id: 80,
                name: 'Вино красное CHATEAUNEUF-DU-PAPE Chateau Mont-Redon, Valle de la Rhone',
                price: 12500,
                description: '750 мл',
            },
            {
                id: 81,
                name: 'Белое розовое D’ADIMANT ROSE Advini, Languedoc-Roussillon, France',
                price: 4200,
                description: '750 мл',
            },
        ],
    },
    en: {
        Breakfast: [
            {
                id: 28,
                name: 'Fried eggs with toppings of your choice',
                price: 320,
                description:
                    'onion, bacon, mushrooms, cheese, tomatoes, greens',
            },
            {
                id: 29,
                name: 'Omelet with toppings of your choice',
                price: 350,
                description:
                    'onion, bacon, mushrooms, cheese, tomatoes, greens',
            },
            {
                id: 30,
                name: 'Eggs Benedict with bacon and Hollandaise sauce',
                price: 390,
                description: '',
            },
            {
                id: 31,
                name: 'Royal eggs with salmon, spinach and Hollandaise sauce',
                price: 490,
                description: '',
            },
            {
                id: 32,
                name: 'Zucchini pancakes with salmon and ricotta',
                price: 490,
                description: '',
            },
            {
                id: 33,
                name: 'Oatmeal porridge',
                price: 300,
                description: '',
            },
            {
                id: 34,
                name: 'Acai bowl',
                price: 350,
                description: '',
            },
            {
                id: 35,
                name: 'Russian style pancakes',
                price: 300,
                description: 'served with jam and sour cream',
            },
            {
                id: 36,
                name: 'Crispy Belgian waffles',
                price: 330,
                description: '',
            },
            {
                id: 37,
                name: 'Cottage cheese pancakes with seasonal berries and sour cream',
                price: 350,
                description: '',
            },
            {
                id: 38,
                name: 'Salmon caviar with with russian pancakes',
                price: 840,
                description: '',
            },
            {
                id: 8,
                name: 'Black caviar with russian pancakes',
                price: 5200,
                description: '50 gr',
            },
        ],
        'Salads and Snacks': [
            {
                id: 1,
                name: 'Salmon toast with zucchini',
                price: 760,
                description: '',
            },
            {
                id: 2,
                name: 'Avocado toast with poached egg',
                price: 690,
                description: '',
            },
            {
                id: 3,
                name: 'Italian wine set',
                price: 1200,
                description:
                    'italian sausages and cheese, grilled artichokes, olives, crostini',
            },
            {
                id: 4,
                name: 'Caesar salad with chicken',
                price: 750,
                description: '',
            },
            {
                id: 5,
                name: 'Caesar salad with tiger shrimps',
                price: 880,
                description: '',
            },
            {
                id: 6,
                name: 'Warm salad with beef',
                price: 710,
                description: '',
            },
            {
                id: 7,
                name: 'Seasonal vegetables with halloumi',
                price: 740,
                description: '',
            },
        ],
        Soups: [
            {
                id: 9,
                name: 'Borsch with garlic bread rolls and sour cream',
                price: 640,
                description: '',
            },
            {
                id: 10,
                name: 'Chicken broth with noodles',
                price: 520,
                description: '',
            },
        ],
        'Burgers and Sandwiches': [
            {
                id: 11,
                name: 'Cayenne burger ',
                price: 1200,
                description:
                    'Marbled beef patty, grilled vegetables, sauce with cayenne pepper Served with French fries and homemade sauces',
            },
            {
                id: 12,
                name: 'Domina cheeseburger',
                price: 1200,
                description:
                    'Marbled beef patty, Cheddar, cucmber relish. Served with French fries and homemade sauces',
            },
            {
                id: 13,
                name: 'Chicken wrap',
                price: 750,
                description: '',
            },
            {
                id: 14,
                name: 'Club sandwich',
                price: 980,
                description:
                    'Served with French fries and homemade sauces',
            },
        ],
        'Main Dishes': [
            {
                id: 15,
                name: 'Halibut with eggplant cream',
                price: 1350,
                description: '',
            },
            {
                id: 16,
                name: 'Flank steak with potato',
                price: 1100,
                description: '',
            },
            {
                id: 17,
                name: 'Sauteed king prawns and squid',
                price: 1300,
                description: '',
            },
            {
                id: 18,
                name: 'Spaghetti alla carbonara',
                price: 720,
                description: '',
            },
            {
                id: 19,
                name: 'Rigatoni cacio e pepe',
                price: 650,
                description: '',
            },
            {
                id: 20,
                name: 'Asian style crispy eggplant',
                price: 640,
                description: '',
            },
        ],
        Desserts: [
            {
                id: 21,
                name: 'Chocolate brownie with ice-cream',
                price: 550,
                description: '',
            },
            {
                id: 22,
                name: 'The Napoleon cake',
                price: 510,
                description: '',
            },
            {
                id: 23,
                name: 'Fruit plate',
                price: 900,
                description: '',
            },
            {
                id: 24,
                name: 'Italian cheese plate',
                price: 950,
                description: '',
            },
            {
                id: 25,
                name: 'Homemade ice-cream and sorbet',
                price: 650,
                description: '',
            },
        ],
        'Non-alcoholic beverages': [
            {
                id: 26,
                name: 'Freshly squeezed orange juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 27,
                name: 'Freshly squeezed grapefruit juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 39,
                name: 'Freshly squeezed apple juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 40,
                name: 'Freshly squeezed carrot juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 41,
                name: 'Freshly squeezed pineapple juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 42,
                name: 'Freshly squeezed celery juices',
                price: 350,
                description: '250 ml',
            },
            {
                id: 43,
                name: 'Mineral Water San Benedetto',
                price: 390,
                description: '250 ml',
            },
            {
                id: 44,
                name: 'Mineral Water San Benedetto',
                price: 750,
                description: '750 ml',
            },
            {
                id: 45,
                name: 'Coffee Espresso',
                price: 250,
                description: '',
            },
            {
                id: 46,
                name: 'Coffee Americano',
                price: 250,
                description: '',
            },
            {
                id: 47,
                name: 'Coffee Cappuccino',
                price: 300,
                description: '',
            },
            {
                id: 48,
                name: 'Coffee Latte',
                price: 300,
                description: '',
            },
            {
                id: 49,
                name: 'Black Tea',
                price: 400,
                description: '400 ml',
            },
            {
                id: 50,
                name: 'Green Tea',
                price: 350,
                description: '400 ml',
            },
            {
                id: 51,
                name: 'Fruit and herbal Tea',
                price: 350,
                description: '400 ml',
            },
        ],
        'Alcoholic Beverages': [
            {
                id: 52,
                name: 'Bottled beer Budels Capucijn',
                price: 580,
                description: '330 ml',
            },
            {
                id: 53,
                name: 'Bottled beer Budels Witte Parel',
                price: 580,
                description: '330 ml',
            },
            {
                id: 54,
                name: 'Royal Demi-Sec Apple Cider',
                price: 420,
                description: '330 ml',
            },
            {
                id: 82,
                name: 'Non-alcohol beer Budels Malt',
                price: 420,
                description: '330 мл',
            },
            {
                id: 55,
                name: 'Vermouth Martini Bianco',
                price: 350,
                description: '50 ml',
            },
            {
                id: 56,
                name: 'Bitter Jagermeister',
                price: 560,
                description: '50 ml',
            },
            {
                id: 57,
                name: 'Vodka Абсолют',
                price: 350,
                description: '50 ml',
            },
            {
                id: 58,
                name: 'Vodka Beluga',
                price: 490,
                description: '50 ml',
            },
            {
                id: 59,
                name: 'Gin Beefeater',
                price: 650,
                description: '50 ml',
            },
            {
                id: 60,
                name: 'Rum Angostura 5 y.o.',
                price: 500,
                description: '50 ml',
            },
            {
                id: 61,
                name: 'Whisky The Macallan 12 y.o.',
                price: 1600,
                description: '50 ml',
            },
            {
                id: 62,
                name: 'Whisky Chivas Regal 12 y.o.',
                price: 990,
                description: '50 ml',
            },
            {
                id: 63,
                name: 'Whisky Jameson',
                price: 690,
                description: '50 ml',
            },
            {
                id: 64,
                name: 'Whisky Jack Daniel’s',
                price: 750,
                description: '50 ml',
            },
            {
                id: 65,
                name: 'Cognac Hennessy Very Special',
                price: 1050,
                description: '50 ml',
            },
            {
                id: 66,
                name: 'Sparkling wine PROSECCO Cielo Brut, Veneto, Italy',
                price: 3900,
                description: '750 ml',
            },
            {
                id: 67,
                name: 'Sparkling wine CRÉMANT D’ALSACE Wolfberger Brut Rosé, Alsace, France',
                price: 7900,
                description: '750 ml',
            },
            {
                id: 68,
                name: 'Champagne Moët & Chandon Brut Imperial, France',
                price: 16500,
                description: '750 ml',
            },
            {
                id: 69,
                name: 'Champagne Moët & Chandon Rosé Brut Imperial, France',
                price: 19500,
                description: '750 ml',
            },
            {
                id: 70,
                name: 'Champagne Veuve Cliquot Brut St.Petersburg, France',
                price: 17500,
                description: '750 ml',
            },
            {
                id: 71,
                name: 'White wines GRUNER VELTLINER Nastl Kittmannsberg, Austria',
                price: 5400,
                description: '750 ml',
            },
            {
                id: 72,
                name: 'White wines SAUVIGNON BLANC Spencer Hill ‘Latitude 41’, New Zealand',
                price: 5900,
                description: '750 ml',
            },
            {
                id: 73,
                name: 'White wines PINOT GRIGIO Elena Walch, Italy',
                price: 6700,
                description: '750 ml',
            },
            {
                id: 74,
                name: 'White wines CHABLIS Jean-Marc Brocard Sainte-Claire, Burgundy, France',
                price: 8200,
                description: '750 ml',
            },
            {
                id: 75,
                name: 'White wines PINOT GRIS Moenchberg Grand Cru ‘Le Moine’, Alsace, France',
                price: 12500,
                description: '750 ml',
            },
            {
                id: 76,
                name: 'Red wines ZWEIGELT Blauer Nittnaus, Austria',
                price: 5400,
                description: '750 ml',
            },
            {
                id: 77,
                name: 'Red wines ZINFANDEL ‘Old Vine Zin’ Gnarly Head, California',
                price: 6400,
                description: '750 ml',
            },
            {
                id: 78,
                name: 'Red wines CHIANTI Classico ReservaSan Felice il Grigio, Toscana',
                price: 81000,
                description: '750 ml',
            },
            {
                id: 79,
                name: 'Red wines SEXY BEAST Two Hands, McLaren Vale, Australia',
                price: 9300,
                description: '750 ml',
            },
            {
                id: 80,
                name: 'Red wines CHATEAUNEUF-DU-PAPE Chateau Mont-Redon, Valle de la Rhone',
                price: 12500,
                description: '750 ml',
            },
            {
                id: 81,
                name: 'Rose wine D’ADIMANT ROSE Advini, Languedoc-Roussillon, France',
                price: 4200,
                description: '750 ml',
            },
        ],
    },
};

export default data;
